const FETCH_REQUEST = 'FETCH_REQESTED';
const FETCH_FAILURE = 'FETCH_FAILURE';
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';

export {FETCH_REQUEST, FETCH_FAILURE, FETCH_BOOKS_SUCCESS, FETCH_BOOK_SUCCESS, FETCH_CHARACTER_SUCCESS};